name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker Image
      run: docker build -t your-image-name .
    
    - name: Run Tests
      run: |
        echo "Running tests..."
        echo "Test"